package com.example.bankmonitor;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.ContentResolver;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.view.WindowManager;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final int SMS_PERMISSION=10;
    private final int INK=Color.rgb(20,31,48), MUTED=Color.rgb(104,119,139), BG=Color.rgb(246,248,252);
    private final int PRIMARY=Color.rgb(54,92,222), GREEN=Color.rgb(17,153,116), RED=Color.rgb(229,76,86);
    private LinearLayout content, nav;
    private TextView headerTitle, headerSub;
    private TransactionDb db;
    private String page="Home", selectedMonth, selectedBank="Commercial";

    @Override protected void onCreate(Bundle state){
        super.onCreate(state);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);
        if(android.os.Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(true);
        selectedMonth=new SimpleDateFormat("yyyy-MM",Locale.US).format(new Date());
        db=new TransactionDb(this);
        setContentView(buildShell());
        requestSmsPermissions();
        open("Home");
    }

    private View buildShell(){
        getWindow().setStatusBarColor(Color.WHITE);getWindow().setNavigationBarColor(Color.WHITE);
        if(android.os.Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(20),dp(12),dp(14),dp(12));header.setBackgroundColor(Color.WHITE);
        LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);
        headerTitle=txt("Money Monitor",24,true,INK);headerSub=txt("Your finances, automatically organized",12,false,MUTED);words.addView(headerTitle);words.addView(headerSub);
        header.addView(words,new LinearLayout.LayoutParams(0,-2,1));
        TextView refresh=action("↻",PRIMARY);refresh.setContentDescription("Refresh bank SMS");refresh.setOnClickListener(v->refreshInbox());header.addView(refresh,new LinearLayout.LayoutParams(dp(48),dp(48)));
        root.addView(header);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(4),dp(5),dp(4),dp(5));nav.setBackgroundColor(Color.WHITE);
        String[] items={"Home","Transactions","Analytics","Accounts","Settings"};int[] icons={R.drawable.nav_home,R.drawable.nav_transactions,R.drawable.nav_analytics,R.drawable.nav_accounts,R.drawable.nav_settings};
        for(int i=0;i<items.length;i++){String item=items[i];TextView b=txt(item,11,true,MUTED);b.setGravity(Gravity.CENTER);b.setCompoundDrawablesWithIntrinsicBounds(0,icons[i],0,0);b.setCompoundDrawablePadding(-dp(4));b.setIncludeFontPadding(false);b.setOnClickListener(v->open(item));nav.addView(b,new LinearLayout.LayoutParams(0,dp(76),1));}
        LinearLayout.LayoutParams navParams=new LinearLayout.LayoutParams(-1,dp(84));root.addView(nav,navParams);
        root.setOnApplyWindowInsetsListener((v,i)->{int top=0,bottom=0;if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets x=i.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}header.setPadding(dp(20),dp(12)+top,dp(14),dp(12));nav.setPadding(dp(4),dp(4),dp(4),dp(4)+bottom);navParams.height=dp(84)+bottom;nav.setLayoutParams(navParams);return i;});
        root.requestApplyInsets();return root;
    }

    private void open(String p){page=p;content.removeAllViews();headerTitle.setText(p.equals("Home")?"Money Monitor":p);headerSub.setText(subtitle(p));if(p.equals("Home"))home();else if(p.equals("Transactions"))transactions();else if(p.equals("Analytics"))analytics();else if(p.equals("Accounts"))accounts();else settings();}
    private String subtitle(String p){if(p.equals("Home"))return "Your finances, automatically organized";if(p.equals("Transactions"))return "Review and correct every movement";if(p.equals("Analytics"))return "Understand where your money goes";if(p.equals("Accounts"))return "Bank and cash balances in one place";return "Automation, categories and backup";}

    private void home(){
        filters();double income=db.total("Credit",selectedMonth,selectedBank),spend=db.total("Debit",selectedMonth,selectedBank);double opening=db.monthBoundaryBalance(selectedMonth,selectedBank,true),closing=db.monthBoundaryBalance(selectedMonth,selectedBank,false);
        content.addView(monthBalanceHero(opening,closing,income,spend));
        content.addView(section("Spending overview"),lp(0,22,0,8));
        Map<String,Double> cats=db.categoryTotals(selectedMonth,selectedBank);if(cats.isEmpty())content.addView(empty("No Commercial transactions for this month yet."));else{int shown=0;for(Map.Entry<String,Double> e:cats.entrySet()){content.addView(categoryRow(e.getKey(),e.getValue(),spend),lp(0,0,0,8));if(++shown==5)break;}}
        content.addView(section("Recent activity"),lp(0,18,0,8));for(TransactionRecord r:db.recent(6,selectedMonth,selectedBank))content.addView(txRow(r),lp(0,0,0,8));
    }

    private void transactions(){filters();TextView add=primaryButton("＋  Add transaction");add.setOnClickListener(v->manualDialog());content.addView(add,lp(0,0,0,14));List<TransactionRecord> rows=db.recent(500,selectedMonth,selectedBank);if(rows.isEmpty())content.addView(empty("No transactions match this selection."));String last="";SimpleDateFormat f=new SimpleDateFormat("dd MMM yyyy",Locale.US);for(TransactionRecord r:rows){String d=f.format(new Date(r.date));if(!d.equals(last)){content.addView(label(d),lp(2,12,0,7));last=d;}content.addView(txRow(r),lp(0,0,0,8));}}

    private void analytics(){filters();double spend=db.total("Debit",selectedMonth,selectedBank),income=db.total("Credit",selectedMonth,selectedBank);Map<String,Double> cats=db.categoryTotals(selectedMonth,selectedBank);content.addView(balanceHero(income-spend,income,spend));if(!cats.isEmpty()){Map.Entry<String,Double> top=cats.entrySet().iterator().next();content.addView(topCategory(top.getKey(),top.getValue(),spend),lp(0,16,0,0));content.addView(section("Expense distribution"),lp(0,22,0,8));content.addView(new DonutChart(cats,spend),new LinearLayout.LayoutParams(-1,dp(230)));}content.addView(section("Monthly category breakdown"),lp(0,22,0,8));if(cats.isEmpty())content.addView(empty("No spending data for this month and bank."));for(Map.Entry<String,Double> e:cats.entrySet())content.addView(categoryRow(e.getKey(),e.getValue(),spend),lp(0,0,0,8));int year=Calendar.getInstance().get(Calendar.YEAR);try{if(selectedMonth!=null&&!selectedMonth.isEmpty())year=Integer.parseInt(selectedMonth.substring(0,4));}catch(Exception ignored){}double[] yearlySpend=db.monthlySpending(year,selectedBank),yearlyIncome=db.monthlyIncome(year,selectedBank);content.addView(section(year+" income vs expenses"),lp(0,24,0,8));content.addView(new CashFlowChart(yearlyIncome,yearlySpend),new LinearLayout.LayoutParams(-1,dp(255)));content.addView(section(year+" spending trend"),lp(0,24,0,8));content.addView(new MonthlyBarChart(yearlySpend),new LinearLayout.LayoutParams(-1,dp(245)));}

    private void accounts(){content.addView(section("Your accounts"),lp(0,0,0,8));for(String a:db.accounts())content.addView(accountCard(a),lp(0,0,0,10));TextView add=primaryButton("＋  Add account");add.setOnClickListener(v->accountDialog());content.addView(add,lp(0,12,0,0));content.addView(empty("SMS transactions are assigned automatically. Tap any transaction to correct its account."),lp(0,14,0,0));}

    private void settings(){content.addView(section("Monthly balances"));filters();if(selectedMonth==null||selectedMonth.isEmpty())content.addView(empty("Select a month to correct its opening or closing balance."));else{content.addView(boundaryCard(true),lp(0,0,0,10));content.addView(boundaryCard(false));content.addView(empty("Manual corrections stay active while new transactions continue updating the closing balance. Use Reset to Auto to return to automatic calculation."),lp(0,12,0,0));}content.addView(section("Automation"),lp(0,24,0,0));TextView scan=primaryButton("Import / refresh bank SMS");scan.setOnClickListener(v->refreshInbox());content.addView(scan,lp(0,10,0,14));content.addView(empty("The app reads only Commercial, Sampath and Seylan transaction alerts. OTP messages are not stored."));content.addView(section("Categories"),lp(0,24,0,8));for(String c:db.categories())content.addView(categoryChip(c),lp(0,0,0,6));TextView add=outlineButton("＋  Add category");add.setOnClickListener(v->categoryDialog());content.addView(add,lp(0,10,0,0));}

    private void filters(){LinearLayout row=card();row.setPadding(dp(10),dp(4),dp(10),dp(4));Spinner month=new Spinner(this);List<String> labels=new ArrayList<>(),values=new ArrayList<>();Calendar now=Calendar.getInstance();for(int i=0;i<12;i++){Calendar c=(Calendar)now.clone();c.add(Calendar.MONTH,-i);labels.add(new SimpleDateFormat("MMMM yyyy",Locale.US).format(c.getTime()));values.add(new SimpleDateFormat("yyyy-MM",Locale.US).format(c.getTime()));}labels.add("All months");values.add("");month.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));month.setSelection(Math.max(0,values.indexOf(selectedMonth)));Spinner bank=new Spinner(this);String[] banks={"Commercial","Sampath","Seylan","Cash","All banks"};bank.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,banks));bank.setSelection(selectedBank.equals("Commercial")?0:selectedBank.equals("Sampath")?1:selectedBank.equals("Seylan")?2:selectedBank.equals("Cash")?3:4);row.addView(month,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(bank,new LinearLayout.LayoutParams(0,dp(52),1));final boolean[] ready={false};month.setOnItemSelectedListener(new SimpleSelect(){public void selected(int pos){if(ready[0]&&!selectedMonth.equals(values.get(pos))){selectedMonth=values.get(pos);open(page);}}});bank.setOnItemSelectedListener(new SimpleSelect(){public void selected(int pos){String b=pos==4?"":banks[pos];if(ready[0]&&!selectedBank.equals(b)){selectedBank=b;open(page);}}});content.addView(row,lp(0,0,0,14));ready[0]=true;}

    private View balanceHero(double balance,double income,double spend){LinearLayout box=card();box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(18),dp(20),dp(18));box.setBackground(round(PRIMARY,22));TextView cap=txt("NET CASH FLOW",11,true,0xFFC9D5FF);TextView big=txt(money(balance),28,true,Color.WHITE);box.addView(cap);box.addView(big,lp(0,5,0,16));LinearLayout row=new LinearLayout(this);row.addView(metric("Income",income,GREEN),new LinearLayout.LayoutParams(0,-2,1));row.addView(metric("Expenses",spend,RED),new LinearLayout.LayoutParams(0,-2,1));box.addView(row);return box;}
    private View monthBalanceHero(double opening,double closing,double income,double spend){LinearLayout box=card();box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(18),dp(20),dp(18));box.setBackground(round(PRIMARY,22));box.addView(txt("CURRENT / CLOSING BALANCE",11,true,0xFFC9D5FF));box.addView(txt(money(closing),28,true,Color.WHITE),lp(0,5,0,5));box.addView(txt("Opening balance  "+money(opening),12,false,0xFFDCE4FF),lp(0,0,0,16));LinearLayout row=new LinearLayout(this);row.addView(metric("Income",income,GREEN),new LinearLayout.LayoutParams(0,-2,1));row.addView(metric("Expenses",spend,RED),new LinearLayout.LayoutParams(0,-2,1));box.addView(row);return box;}
    private View metric(String name,double value,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);TextView a=txt(name,12,false,0xFFDCE4FF);TextView b=txt(money(value),15,true,Color.WHITE);x.addView(a);x.addView(b,lp(0,3,0,0));return x;}
    private View topCategory(String name,double value,double total){LinearLayout box=card();box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(18),dp(16),dp(18),dp(16));TextView icon=action("★",color(name));box.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));box.addView(new Space(this),new LinearLayout.LayoutParams(dp(10),1));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(txt("HIGHEST SPENDING",10,true,MUTED));words.addView(txt(name,17,true,INK));words.addView(txt(total>0?Math.round(value/total*100)+"% of monthly expenses":"",12,false,MUTED));box.addView(words,new LinearLayout.LayoutParams(0,-2,1));box.addView(txt(money(value),14,true,RED));return box;}
    private View categoryRow(String name,double value,double total){LinearLayout box=card();box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));TextView icon=txt("●",18,true,color(name));box.addView(icon);LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(txt(name,14,true,INK));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);bar.setProgress(total<=0?0:(int)(value/total*1000));bar.setProgressTintList(android.content.res.ColorStateList.valueOf(color(name)));words.addView(bar,new LinearLayout.LayoutParams(-1,dp(5)));box.addView(words,new LinearLayout.LayoutParams(0,-2,1));TextView amount=txt(money(value),13,true,INK);box.addView(amount);return box;}
    private View txRow(TransactionRecord r){LinearLayout box=card();box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(14),dp(13),dp(14),dp(13));TextView icon=action(r.type.equals("Debit")?"−":"+",r.type.equals("Debit")?RED:GREEN);box.addView(icon,new LinearLayout.LayoutParams(dp(36),dp(36)));box.addView(new Space(this),new LinearLayout.LayoutParams(dp(10),1));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);TextView d=txt(r.description,14,true,INK);d.setMaxLines(2);words.addView(d);words.addView(txt(r.bank+" • "+r.account+" • "+r.category,11,false,MUTED));if(r.note!=null&&!r.note.trim().isEmpty())words.addView(txt("Note: "+r.note,11,false,PRIMARY));box.addView(words,new LinearLayout.LayoutParams(0,-2,1));LinearLayout side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setGravity(Gravity.END);TextView a=txt((r.type.equals("Debit")?"− ":"+ ")+money(r.amount),13,true,r.type.equals("Debit")?RED:GREEN);side.addView(a);if("Manual".equals(r.sender)){TextView del=txt("Delete",11,true,RED);del.setGravity(Gravity.CENTER);del.setPadding(dp(8),dp(4),dp(8),dp(4));del.setBackground(round(0xFFFFE8EA,10));del.setOnClickListener(v->confirmDelete(r));side.addView(del,lp(0,6,0,0));}box.addView(side);box.setOnClickListener(v->editDialog(r));return box;}
    private View accountCard(String name){LinearLayout box=card();box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(16),dp(15),dp(16),dp(15));TextView icon=action(name.equals("Cash")?"C":"B",name.equals("Cash")?GREEN:PRIMARY);box.addView(icon,new LinearLayout.LayoutParams(dp(38),dp(38)));box.addView(new Space(this),new LinearLayout.LayoutParams(dp(10),1));LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);w.addView(txt(name,16,true,INK));w.addView(txt(name.equals("Cash")?"Cash balance • tap to update":"Available balance • tap to update",12,false,MUTED));box.addView(w,new LinearLayout.LayoutParams(0,-2,1));double balance=db.accountBalance(name);box.addView(txt(money(balance),13,true,balance<0?RED:GREEN));box.setOnClickListener(v->balanceDialog(name));return box;}
    private View boundaryCard(boolean opening){Double manual=db.manualBoundaryBalance(selectedMonth,selectedBank,opening);double applied=db.monthBoundaryBalance(selectedMonth,selectedBank,opening);LinearLayout box=card();box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(16),dp(14),dp(14),dp(14));TextView icon=action(opening?"O":"C",opening?PRIMARY:GREEN);box.addView(icon,new LinearLayout.LayoutParams(dp(38),dp(38)));box.addView(new Space(this),new LinearLayout.LayoutParams(dp(10),1));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(txt(opening?"Opening balance":"Closing balance",15,true,INK));words.addView(txt(manual==null?"Automatic calculation":"Manual override • auto-updates continue",11,false,manual==null?MUTED:PRIMARY));box.addView(words,new LinearLayout.LayoutParams(0,-2,1));LinearLayout side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setGravity(Gravity.END);side.addView(txt(money(applied),13,true,applied<0?RED:GREEN));side.addView(txt("Edit",11,true,PRIMARY),lp(0,4,0,0));box.addView(side);box.setOnClickListener(v->boundaryDialog(opening));return box;}

    private void manualDialog(){LinearLayout f=form();Spinner account=spinner(Arrays.asList("Commercial - Saving","Cash"));Spinner type=spinner(Arrays.asList("Expense","Income"));EditText amount=input("Amount (LKR)",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Spinner category=spinner(db.categories());EditText description=input("Description",InputType.TYPE_CLASS_TEXT);f.addView(account);f.addView(type);f.addView(amount);f.addView(category);f.addView(description);new AlertDialog.Builder(this).setTitle("Add transaction").setView(f).setPositiveButton("Save",(d,w)->{try{double x=Double.parseDouble(amount.getText().toString());String ac=account.getSelectedItem().toString();String bank=bankFor(ac);db.insertManual(ac,bank,type.getSelectedItemPosition()==0?"Debit":"Credit",x,category.getSelectedItem().toString(),description.getText().toString().trim(),System.currentTimeMillis());open(page);}catch(Exception e){toast("Enter a valid amount");}}).setNegativeButton("Cancel",null).show();}
    private void editDialog(TransactionRecord r){LinearLayout f=form();Spinner account=spinner(db.accounts());account.setSelection(Math.max(0,db.accounts().indexOf(r.account)));Spinner cat=spinner(db.categories());cat.setSelection(Math.max(0,db.categories().indexOf(r.category)));EditText note=input("Note (optional)",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES|InputType.TYPE_TEXT_FLAG_MULTI_LINE);note.setText(r.note==null?"":r.note);note.setMinLines(2);f.addView(account);f.addView(cat);f.addView(note);new AlertDialog.Builder(this).setTitle("Edit transaction").setView(f).setPositiveButton("Save",(d,w)->{db.updateLabels(r.id,account.getSelectedItem().toString(),cat.getSelectedItem().toString(),note.getText().toString().trim());open(page);}).setNegativeButton("Cancel",null).show();}
    private void confirmDelete(TransactionRecord r){new AlertDialog.Builder(this).setTitle("Delete manual transaction?").setMessage(r.description+"\n"+money(r.amount)).setPositiveButton("Delete",(d,w)->{db.deleteManual(r.id);open(page);}).setNegativeButton("Cancel",null).show();}
    private void categoryDialog(){EditText n=input("Category name",InputType.TYPE_CLASS_TEXT);new AlertDialog.Builder(this).setTitle("New category").setView(n).setPositiveButton("Add",(d,w)->{if(!n.getText().toString().trim().isEmpty())db.addCategory(n.getText().toString());open(page);}).setNegativeButton("Cancel",null).show();}
    private void accountDialog(){LinearLayout f=form();EditText name=input("Account name",InputType.TYPE_CLASS_TEXT);Spinner bank=spinner(Arrays.asList("Commercial","Sampath","Seylan","Cash"));f.addView(name);f.addView(bank);new AlertDialog.Builder(this).setTitle("New account").setView(f).setPositiveButton("Add",(d,w)->{if(!name.getText().toString().trim().isEmpty())db.addAccount(name.getText().toString(),bank.getSelectedItem().toString());open(page);}).setNegativeButton("Cancel",null).show();}
    private void balanceDialog(String account){EditText value=input("Current available balance (LKR)",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);value.setText(String.format(Locale.US,"%.2f",db.accountBalance(account)));new AlertDialog.Builder(this).setTitle(account+" balance").setView(value).setPositiveButton("Save",(d,w)->{try{db.setAccountBalance(account,Double.parseDouble(value.getText().toString()));open("Accounts");}catch(Exception e){toast("Enter a valid balance");}}).setNegativeButton("Cancel",null).show();}
    private void boundaryDialog(boolean opening){double current=db.monthBoundaryBalance(selectedMonth,selectedBank,opening);Double manual=db.manualBoundaryBalance(selectedMonth,selectedBank,opening);EditText value=input((opening?"Opening":"Closing")+" balance (LKR)",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);value.setText(String.format(Locale.US,"%.2f",current));AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle((opening?"Opening":"Closing")+" balance correction").setMessage(selectedMonth+" • "+(selectedBank.isEmpty()?"All banks":selectedBank)).setView(value).setPositiveButton("Save override",(d,w)->{try{db.setManualBoundaryBalance(selectedMonth,selectedBank,opening,Double.parseDouble(value.getText().toString()));open("Settings");}catch(Exception e){toast("Enter a valid balance");}}).setNegativeButton("Cancel",null);if(manual!=null)b.setNeutralButton("Reset to Auto",(d,w)->{db.clearManualBoundaryBalance(selectedMonth,selectedBank,opening);open("Settings");});b.show();}

    private void refreshInbox(){if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){requestSmsPermissions();toast("Allow SMS permission, then tap refresh again.");return;}headerSub.setText("Scanning bank messages…");new Thread(()->{int added=0;ContentResolver cr=getContentResolver();try(Cursor c=cr.query(Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date ASC")){if(c!=null)while(c.moveToNext()){String sender=c.getString(0);if(!BankSmsReceiver.isAcceptedSender(sender))continue;TransactionRecord r=BankMessageParser.parse(sender,c.getString(1),c.getLong(2));if(r!=null&&db.insert(r))added++;}}catch(Exception ignored){}int a=added;runOnUiThread(()->{toast("Added "+a+" new transactions");open(page);});}).start();}

    private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setBackground(round(Color.WHITE,18));return x;}
    private TextView section(String s){return txt(s,18,true,INK);}private TextView label(String s){return txt(s,12,true,MUTED);}private TextView empty(String s){TextView t=txt(s,13,false,MUTED);t.setPadding(dp(16),dp(14),dp(16),dp(14));t.setBackground(round(Color.WHITE,16));return t;}
    private TextView primaryButton(String s){TextView t=txt(s,14,true,Color.WHITE);t.setGravity(Gravity.CENTER);t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackground(round(PRIMARY,16));return t;}private TextView outlineButton(String s){TextView t=txt(s,14,true,PRIMARY);t.setGravity(Gravity.CENTER);t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackground(round(0xFFE8EDFF,16));return t;}
    private TextView categoryChip(String s){TextView t=txt("●   "+s,14,false,INK);t.setPadding(dp(14),dp(11),dp(14),dp(11));t.setBackground(round(Color.WHITE,14));return t;}
    private TextView action(String s,int color){TextView t=txt(s,20,true,Color.WHITE);t.setGravity(Gravity.CENTER);t.setBackground(round(color,14));return t;}
    private TextView txt(String s,int size,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),0,dp(20),0);return f;}private EditText input(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setInputType(type);return e;}private Spinner spinner(List<String> values){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));return s;}
    private android.graphics.drawable.Drawable round(int color,int radius){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}private LinearLayout.LayoutParams lp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private String money(double v){return String.format(Locale.US,"LKR %,.2f",v);}private int color(String s){int[] c={0xFF4361EE,0xFFEF8354,0xFF2A9D8F,0xFF9B5DE5,0xFFF15BB5,0xFF00A8E8};return c[Math.abs(s.hashCode())%c.length];}private String bankFor(String account){if(account.startsWith("Commercial"))return "Commercial";if(account.startsWith("Sampath"))return "Sampath";if(account.startsWith("Seylan"))return "Seylan";return "Cash";}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void requestSmsPermissions(){if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},SMS_PERMISSION);}
    private class DonutChart extends View{private final Map<String,Double> data;private final double total;private final Paint p=new Paint(1);DonutChart(Map<String,Double>d,double t){super(MainActivity.this);data=new LinkedHashMap<>(d);total=Math.max(1,t);setBackground(round(Color.WHITE,18));}protected void onDraw(Canvas c){super.onDraw(c);float cx=dp(105),cy=getHeight()/2f,r=dp(68);RectF oval=new RectF(cx-r,cy-r,cx+r,cy+r);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(25));p.setStrokeCap(Paint.Cap.BUTT);float start=-90;int i=0;for(Map.Entry<String,Double>e:data.entrySet()){float sweep=(float)(e.getValue()/total*360);p.setColor(color(e.getKey()));c.drawArc(oval,start,sweep,false,p);start+=sweep;i++;}p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(MUTED);p.setTextSize(dp(10));c.drawText("EXPENSES",cx,cy-dp(5),p);p.setColor(INK);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(13));c.drawText(money(total).replace("LKR ",""),cx,cy+dp(15),p);p.setTextAlign(Paint.Align.LEFT);p.setTypeface(Typeface.DEFAULT);float x=dp(200),y=dp(42);i=0;for(Map.Entry<String,Double>e:data.entrySet()){if(i++>=5)break;p.setColor(color(e.getKey()));c.drawCircle(x,y-dp(4),dp(4),p);p.setColor(INK);p.setTextSize(dp(11));c.drawText(e.getKey(),x+dp(12),y,p);p.setColor(MUTED);p.setTextSize(dp(10));c.drawText(Math.round(e.getValue()/total*100)+"%",x+dp(12),y+dp(15),p);y+=dp(35);}}}
    private class CashFlowChart extends View{private final double[] income,expense;private final Paint p=new Paint(1);private final String[] m={"J","F","M","A","M","J","J","A","S","O","N","D"};CashFlowChart(double[]i,double[]e){super(MainActivity.this);income=i;expense=e;setBackground(round(Color.WHITE,18));}protected void onDraw(Canvas c){super.onDraw(c);float left=dp(14),right=getWidth()-dp(14),top=dp(40),bottom=getHeight()-dp(32),slot=(right-left)/12f,w=slot*0.27f;double max=1;for(double v:income)max=Math.max(max,v);for(double v:expense)max=Math.max(max,v);p.setStyle(Paint.Style.FILL);p.setTextSize(dp(10));p.setColor(GREEN);c.drawCircle(left+dp(4),dp(18),dp(4),p);p.setColor(MUTED);c.drawText("Income",left+dp(14),dp(22),p);p.setColor(RED);c.drawCircle(left+dp(82),dp(18),dp(4),p);p.setColor(MUTED);c.drawText("Expenses",left+dp(92),dp(22),p);p.setTextAlign(Paint.Align.CENTER);for(int n=0;n<12;n++){float x=left+slot*n+slot/2,hi=(float)(income[n]/max*(bottom-top)),he=(float)(expense[n]/max*(bottom-top));p.setColor(GREEN);c.drawRoundRect(x-w-dp(1),bottom-hi,x-dp(1),bottom,dp(3),dp(3),p);p.setColor(RED);c.drawRoundRect(x+dp(1),bottom-he,x+w+dp(1),bottom,dp(3),dp(3),p);p.setColor(MUTED);p.setTextSize(dp(9));c.drawText(m[n],x,getHeight()-dp(11),p);}p.setTextAlign(Paint.Align.LEFT);}}
    private class MonthlyBarChart extends View{private final double[] values;private final Paint paint=new Paint(1);private final String[] months={"J","F","M","A","M","J","J","A","S","O","N","D"};MonthlyBarChart(double[] v){super(MainActivity.this);values=v;setBackground(round(Color.WHITE,18));setPadding(dp(12),dp(12),dp(12),dp(8));}protected void onDraw(Canvas c){super.onDraw(c);float left=dp(14),right=getWidth()-dp(14),top=dp(22),bottom=getHeight()-dp(34);double max=1;for(double v:values)max=Math.max(max,v);float slot=(right-left)/12f,bar=slot*0.52f;paint.setTextAlign(Paint.Align.CENTER);paint.setTypeface(Typeface.DEFAULT_BOLD);for(int i=0;i<12;i++){float x=left+slot*i+slot/2;float h=(float)((values[i]/max)*(bottom-top));paint.setColor(values[i]>0?PRIMARY:0xFFE8EDF5);c.drawRoundRect(x-bar/2,bottom-h,x+bar/2,bottom,dp(5),dp(5),paint);paint.setColor(MUTED);paint.setTextSize(dp(10));c.drawText(months[i],x,getHeight()-dp(13),paint);}paint.setTextAlign(Paint.Align.LEFT);paint.setColor(MUTED);paint.setTextSize(dp(10));paint.setTypeface(Typeface.DEFAULT);c.drawText("Highest month: "+money(max),left,dp(15),paint);}}
    private abstract class SimpleSelect implements android.widget.AdapterView.OnItemSelectedListener{public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){selected(pos);}public abstract void selected(int pos);}
}
