package com.example.bankmonitor;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

final class TransactionDb extends SQLiteOpenHelper {
    TransactionDb(Context c){super(c,"bank_monitor.db",null,6);SQLiteDatabase d=getWritableDatabase();ensureBalanceTimestamp(d);ensureNoteColumn(d);ensureBalanceOverrides(d);seedDefaults(d);ensureAtmTransfers(d);ensureInternalTransfers(d);applyRequestedCashAnchor(d);}
    @Override public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE transactions(id TEXT PRIMARY KEY, received INTEGER, tx_date INTEGER, bank TEXT, account TEXT, type TEXT, amount REAL, category TEXT, description TEXT, balance REAL, sender TEXT, raw TEXT)");d.execSQL("CREATE TABLE accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,bank TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");d.execSQL("CREATE TABLE categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,color TEXT)");d.execSQL("CREATE TABLE balance_overrides(month TEXT,bank TEXT,boundary TEXT,amount REAL,set_at INTEGER,PRIMARY KEY(month,bank,boundary))");String[] ac={"Commercial-1|Commercial","Commercial-2|Commercial","Sampath-1|Sampath","Seylan-1|Seylan","Cash|Cash"};for(String x:ac){String[] p=x.split("\\|");ContentValues v=new ContentValues();v.put("name",p[0]);v.put("bank",p[1]);d.insert("accounts",null,v);}String[] cats={"Fuel","Food & Groceries","Phone & Internet","Health","Education & Online","Bank Charges","Cash Withdrawal","Transport","Other"};for(String n:cats){ContentValues v=new ContentValues();v.put("name",n);d.insert("categories",null,v);}d.execSQL("CREATE INDEX tx_date_idx ON transactions(tx_date DESC)");}
    @Override public void onUpgrade(SQLiteDatabase d,int a,int b){if(a<2){d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,bank TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");d.execSQL("CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,color TEXT)");}if(a<5)ensureBalanceOverrides(d);}
    boolean insert(TransactionRecord r){SQLiteDatabase d=getWritableDatabase();ContentValues v=new ContentValues();v.put("id",r.id);v.put("received",r.receivedAt);v.put("tx_date",r.date);v.put("bank",r.bank);v.put("account",r.account);v.put("type",r.type);v.put("amount",r.amount);v.put("category",r.category);v.put("description",r.description);v.put("balance",r.balance);v.put("sender",r.sender);v.put("raw",r.raw);boolean added=d.insertWithOnConflict("transactions",null,v,SQLiteDatabase.CONFLICT_IGNORE)!=-1;if("Debit".equals(r.type)&&"Cash Withdrawal".equals(r.category)&&!"Cash".equals(r.bank)){ContentValues cash=new ContentValues();cash.put("id",r.id+"-cash");cash.put("received",r.receivedAt);cash.put("tx_date",r.date);cash.put("bank","Cash");cash.put("account","Cash");cash.put("type","Credit");cash.put("amount",r.amount);cash.put("category","ATM Transfer");cash.put("description","ATM cash from "+r.bank);cash.put("balance",0);cash.put("sender","Auto Transfer");cash.put("raw",r.raw);d.insertWithOnConflict("transactions",null,cash,SQLiteDatabase.CONFLICT_IGNORE);}return added;}
    boolean updateLabels(String id,String account,String category,String note){ContentValues v=new ContentValues();v.put("account",account);v.put("category",category);v.put("note",note);return getWritableDatabase().update("transactions",v,"id=?",new String[]{id})>0;}
    boolean deleteManual(String id){return getWritableDatabase().delete("transactions","id=? AND sender='Manual'",new String[]{id})>0;}
    boolean addCategory(String name){ContentValues v=new ContentValues();v.put("name",name.trim());return getWritableDatabase().insertWithOnConflict("categories",null,v,SQLiteDatabase.CONFLICT_IGNORE)>0;}
    boolean addAccount(String name,String bank){ContentValues v=new ContentValues();v.put("name",name.trim());v.put("bank",bank);return getWritableDatabase().insertWithOnConflict("accounts",null,v,SQLiteDatabase.CONFLICT_IGNORE)>0;}
    boolean insertManual(String account,String bank,String type,double amount,String category,String description,long date){TransactionRecord r=new TransactionRecord();r.id="manual-"+System.currentTimeMillis();r.receivedAt=System.currentTimeMillis();r.date=date;r.bank=bank;r.account=account;r.type=type;r.amount=amount;r.category=category;r.description=description;r.balance=0;r.sender="Manual";r.raw=description;return insert(r);}
    List<String> accounts(){List<String> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT name FROM accounts WHERE active=1 ORDER BY id",null)){while(c.moveToNext())out.add(c.getString(0));}return out;}
    List<String> categories(){List<String> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT name FROM categories ORDER BY id",null)){while(c.moveToNext())out.add(c.getString(0));}return out;}
    private void ensureBalanceTimestamp(SQLiteDatabase d){boolean found=false;try(Cursor c=d.rawQuery("PRAGMA table_info(accounts)",null)){while(c.moveToNext())if("balance_set_at".equals(c.getString(1)))found=true;}if(!found){d.execSQL("ALTER TABLE accounts ADD COLUMN balance_set_at INTEGER DEFAULT 0");d.execSQL("UPDATE accounts SET balance_set_at="+System.currentTimeMillis()+" WHERE opening_balance<>0");}}
    private void ensureNoteColumn(SQLiteDatabase d){boolean found=false;try(Cursor c=d.rawQuery("PRAGMA table_info(transactions)",null)){while(c.moveToNext())if("note".equals(c.getString(1)))found=true;}if(!found)d.execSQL("ALTER TABLE transactions ADD COLUMN note TEXT DEFAULT ''");}
    private void ensureBalanceOverrides(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS balance_overrides(month TEXT,bank TEXT,boundary TEXT,amount REAL,set_at INTEGER,PRIMARY KEY(month,bank,boundary))");}
    double accountBalance(String account){SQLiteDatabase d=getReadableDatabase();double anchor=0;long anchorTime=0;try(Cursor c=d.rawQuery("SELECT opening_balance,balance_set_at FROM accounts WHERE name=?",new String[]{account})){if(c.moveToFirst()){anchor=c.getDouble(0);anchorTime=c.getLong(1);}}if("Cash".equals(account)&&anchorTime==0){try(Cursor c=d.rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE account='Cash'",null)){return c.moveToFirst()?c.getDouble(0):0;}}if(!"Cash".equals(account)){try(Cursor c=d.rawQuery("SELECT balance,tx_date FROM transactions WHERE account=? AND balance>0 ORDER BY tx_date DESC LIMIT 1",new String[]{account})){if(c.moveToFirst()&&c.getLong(1)>=anchorTime){anchor=c.getDouble(0);anchorTime=c.getLong(1);}}}try(Cursor c=d.rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE account=? AND tx_date>?",new String[]{account,String.valueOf(anchorTime)})){return anchor+(c.moveToFirst()?c.getDouble(0):0);}}
    void setAccountBalance(String account,double balance){ContentValues v=new ContentValues();v.put("opening_balance",balance);v.put("balance_set_at",System.currentTimeMillis());getWritableDatabase().update("accounts",v,"name=?",new String[]{account});}
    double monthBoundaryBalance(String month,String bank,boolean opening){
        if(month==null||month.isEmpty())return currentAvailableTotal(bank);
        try{
            Calendar start=monthStart(month);long startAt=start.getTimeInMillis();Calendar end=(Calendar)start.clone();end.add(Calendar.MONTH,1);long target=Math.min(System.currentTimeMillis(),end.getTimeInMillis()-1);
            BalanceOverride exact=balanceOverride(month,bank,opening?"opening":"closing");
            if(exact!=null){
                if(opening)return exact.amount;
                return exact.amount+netReceivedAfter(bank,exact.setAt,target);
            }
            double openingBase;
            BalanceOverride manualOpening=balanceOverride(month,bank,"opening");
            if(manualOpening!=null)openingBase=manualOpening.amount;
            else{
                Calendar previous=(Calendar)start.clone();previous.add(Calendar.MONTH,-1);String previousMonth=new java.text.SimpleDateFormat("yyyy-MM",java.util.Locale.US).format(previous.getTime());
                BalanceOverride previousClosing=balanceOverride(previousMonth,bank,"closing");
                if(previousClosing!=null)openingBase=previousClosing.amount+netReceivedAfter(bank,previousClosing.setAt,startAt-1);
                else openingBase=automaticBalanceAt(bank,startAt-1);
            }
            if(opening)return openingBase;
            return openingBase+netByDate(bank,startAt,target);
        }catch(Exception e){return currentAvailableTotal(bank);}
    }
    Double manualBoundaryBalance(String month,String bank,boolean opening){BalanceOverride x=balanceOverride(month,bank,opening?"opening":"closing");return x==null?null:x.amount;}
    void setManualBoundaryBalance(String month,String bank,boolean opening,double amount){ContentValues v=new ContentValues();v.put("month",month);v.put("bank",bankKey(bank));v.put("boundary",opening?"opening":"closing");v.put("amount",amount);v.put("set_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("balance_overrides",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    void clearManualBoundaryBalance(String month,String bank,boolean opening){getWritableDatabase().delete("balance_overrides","month=? AND bank=? AND boundary=?",new String[]{month,bankKey(bank),opening?"opening":"closing"});}
    private Calendar monthStart(String month)throws Exception{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("yyyy-MM",java.util.Locale.US);Calendar c=Calendar.getInstance();c.setTime(f.parse(month));c.set(Calendar.DAY_OF_MONTH,1);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c;}
    private String bankKey(String bank){return bank==null||bank.isEmpty()?"__ALL__":bank;}
    private BalanceOverride balanceOverride(String month,String bank,String boundary){try(Cursor c=getReadableDatabase().rawQuery("SELECT amount,set_at FROM balance_overrides WHERE month=? AND bank=? AND boundary=?",new String[]{month,bankKey(bank),boundary})){return c.moveToFirst()?new BalanceOverride(c.getDouble(0),c.getLong(1)):null;}}
    private double automaticBalanceAt(String bank,long target){double total=0;try(Cursor cur=getReadableDatabase().rawQuery("SELECT name,bank FROM accounts WHERE active=1",null)){while(cur.moveToNext())if(bank==null||bank.isEmpty()||bank.equals(cur.getString(1)))total+=accountBalanceAt(cur.getString(0),target);}return total;}
    private double netByDate(String bank,long from,long to){String extra=bank==null||bank.isEmpty()?"":" AND bank=?";String[] args=bank==null||bank.isEmpty()?new String[]{String.valueOf(from),String.valueOf(to)}:new String[]{String.valueOf(from),String.valueOf(to),bank};try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE tx_date>=? AND tx_date<=?"+extra,args)){return c.moveToFirst()?c.getDouble(0):0;}}
    private double netReceivedAfter(String bank,long setAt,long target){String extra=bank==null||bank.isEmpty()?"":" AND bank=?";String[] args=bank==null||bank.isEmpty()?new String[]{String.valueOf(setAt),String.valueOf(target)}:new String[]{String.valueOf(setAt),String.valueOf(target),bank};try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE received>? AND tx_date<=?"+extra,args)){return c.moveToFirst()?c.getDouble(0):0;}}
    private static final class BalanceOverride{final double amount;final long setAt;BalanceOverride(double a,long s){amount=a;setAt=s;}}
    private double currentAvailableTotal(String bank){double total=0;try(Cursor c=getReadableDatabase().rawQuery("SELECT name,bank FROM accounts WHERE active=1",null)){while(c.moveToNext())if(bank==null||bank.isEmpty()||bank.equals(c.getString(1)))total+=accountBalance(c.getString(0));}return total;}
    private double accountBalanceAt(String account,long target){SQLiteDatabase d=getReadableDatabase();double anchor=0;long anchorTime=0;try(Cursor c=d.rawQuery("SELECT opening_balance,balance_set_at FROM accounts WHERE name=?",new String[]{account})){if(c.moveToFirst()){anchor=c.getDouble(0);anchorTime=c.getLong(1);}}if(!"Cash".equals(account)){try(Cursor c=d.rawQuery("SELECT balance,tx_date FROM transactions WHERE account=? AND balance>0 ORDER BY tx_date DESC LIMIT 1",new String[]{account})){if(c.moveToFirst()&&c.getLong(1)>=anchorTime){anchor=c.getDouble(0);anchorTime=c.getLong(1);}}}if(target>=anchorTime){try(Cursor c=d.rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE account=? AND tx_date>? AND tx_date<=?",new String[]{account,String.valueOf(anchorTime),String.valueOf(target)})){return anchor+(c.moveToFirst()?c.getDouble(0):0);}}else{try(Cursor c=d.rawQuery("SELECT COALESCE(SUM(CASE WHEN type='Credit' THEN amount ELSE -amount END),0) FROM transactions WHERE account=? AND tx_date>? AND tx_date<=?",new String[]{account,String.valueOf(target),String.valueOf(anchorTime)})){return anchor-(c.moveToFirst()?c.getDouble(0):0);}}}
    private void applyRequestedCashAnchor(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS app_meta(meta_key TEXT PRIMARY KEY,meta_value TEXT)");ContentValues marker=new ContentValues();marker.put("meta_key","cash_anchor_20_v1");marker.put("meta_value","applied");if(d.insertWithOnConflict("app_meta",null,marker,SQLiteDatabase.CONFLICT_IGNORE)!=-1){ContentValues v=new ContentValues();v.put("opening_balance",20.0);v.put("balance_set_at",System.currentTimeMillis());d.update("accounts",v,"name='Cash'",null);}}
    private void ensureAtmTransfers(SQLiteDatabase d){d.execSQL("UPDATE transactions SET account='Sampath' WHERE bank='Sampath' AND account<>'Cash'");d.execSQL("UPDATE transactions SET account='Seylan' WHERE bank='Seylan' AND account<>'Cash'");d.execSQL("UPDATE transactions SET account='Commercial - Card' WHERE bank='Commercial' AND (account LIKE '%CARD%' OR category='Cash Withdrawal')");d.execSQL("UPDATE transactions SET account='Commercial - Saving' WHERE bank='Commercial' AND account NOT IN ('Commercial - Card','Cash')");ContentValues cat=new ContentValues();cat.put("name","ATM Transfer");d.insertWithOnConflict("categories",null,cat,SQLiteDatabase.CONFLICT_IGNORE);d.execSQL("INSERT OR IGNORE INTO transactions(id,received,tx_date,bank,account,type,amount,category,description,balance,sender,raw) SELECT id||'-cash',received,tx_date,'Cash','Cash','Credit',amount,'ATM Transfer','ATM cash from '||bank,0,'Auto Transfer',raw FROM transactions WHERE type='Debit' AND category='Cash Withdrawal' AND bank<>'Cash'");}
    private void ensureInternalTransfers(SQLiteDatabase d){ContentValues cat=new ContentValues();cat.put("name","Internal Transfer");d.insertWithOnConflict("categories",null,cat,SQLiteDatabase.CONFLICT_IGNORE);d.execSQL("CREATE TABLE IF NOT EXISTS app_meta(meta_key TEXT PRIMARY KEY,meta_value TEXT)");ContentValues marker=new ContentValues();marker.put("meta_key","commercial_internal_transfer_v1");marker.put("meta_value","applied");if(d.insertWithOnConflict("app_meta",null,marker,SQLiteDatabase.CONFLICT_IGNORE)!=-1)d.execSQL("UPDATE transactions SET category='Internal Transfer' WHERE bank='Commercial' AND type='Credit' AND lower(description) LIKE '%digital banking division%' AND category='Income / Deposit'");}
    private void seedDefaults(SQLiteDatabase d){d.execSQL("UPDATE accounts SET name='Commercial - Card' WHERE name='Commercial-1'");d.execSQL("UPDATE accounts SET name='Commercial - Saving' WHERE name='Commercial-2'");d.execSQL("UPDATE accounts SET name='Sampath' WHERE name='Sampath-1'");d.execSQL("UPDATE accounts SET name='Seylan' WHERE name='Seylan-1'");d.execSQL("UPDATE transactions SET account='Commercial - Card' WHERE account='Commercial-1'");d.execSQL("UPDATE transactions SET account='Commercial - Saving' WHERE account='Commercial-2'");d.execSQL("UPDATE transactions SET account='Sampath' WHERE account='Sampath-1'");d.execSQL("UPDATE transactions SET account='Seylan' WHERE account='Seylan-1'");String[] ac={"Commercial - Card|Commercial","Commercial - Saving|Commercial","Sampath|Sampath","Seylan|Seylan","Cash|Cash"};for(String x:ac){String[] p=x.split("\\|");ContentValues v=new ContentValues();v.put("name",p[0]);v.put("bank",p[1]);d.insertWithOnConflict("accounts",null,v,SQLiteDatabase.CONFLICT_IGNORE);}String[] cats={"Fuel","Food & Groceries","Phone & Internet","Health","Education & Online","Bank Charges","Cash Withdrawal","ATM Transfer","Internal Transfer","Transport","Shopping","Bills","Other"};for(String n:cats){ContentValues v=new ContentValues();v.put("name",n);d.insertWithOnConflict("categories",null,v,SQLiteDatabase.CONFLICT_IGNORE);}}
    List<TransactionRecord> recent(int limit,String month,String bank){List<TransactionRecord>a=new ArrayList<>();Filter f=filter(month,bank);try(Cursor c=getReadableDatabase().rawQuery("SELECT id,tx_date,bank,account,type,amount,category,description,balance,sender,raw,received,note FROM transactions WHERE "+f.where+" ORDER BY tx_date DESC LIMIT "+limit,f.args)){while(c.moveToNext()){TransactionRecord r=new TransactionRecord();r.id=c.getString(0);r.date=c.getLong(1);r.bank=c.getString(2);r.account=c.getString(3);r.type=c.getString(4);r.amount=c.getDouble(5);r.category=c.getString(6);r.description=c.getString(7);r.balance=c.getDouble(8);r.sender=c.getString(9);r.raw=c.getString(10);r.receivedAt=c.getLong(11);r.note=c.isNull(12)?"":c.getString(12);a.add(r);}}return a;}
    double total(String type,String month,String bank){Filter f=filter(month,bank);String[] args=new String[f.args.length+1];args[0]=type;System.arraycopy(f.args,0,args,1,f.args.length);try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM transactions WHERE type=? AND category NOT IN ('Cash Withdrawal','ATM Transfer','Internal Transfer') AND "+f.where,args)){return c.moveToFirst()?c.getDouble(0):0;}}
    Map<String,Double> categoryTotals(String month,String bank){Map<String,Double>m=new LinkedHashMap<>();Filter f=filter(month,bank);try(Cursor c=getReadableDatabase().rawQuery("SELECT category,SUM(amount) total FROM transactions WHERE type='Debit' AND category NOT IN ('Cash Withdrawal','ATM Transfer','Internal Transfer') AND "+f.where+" GROUP BY category ORDER BY total DESC",f.args)){while(c.moveToNext())m.put(c.getString(0),c.getDouble(1));}return m;}
    double[] monthlySpending(int year,String bank){double[] out=new double[12];Calendar c=Calendar.getInstance();c.clear();c.set(year,Calendar.JANUARY,1);long from=c.getTimeInMillis();c.add(Calendar.YEAR,1);long to=c.getTimeInMillis();String sql="SELECT CAST(strftime('%m',tx_date/1000,'unixepoch','localtime') AS INTEGER),SUM(amount) FROM transactions WHERE type='Debit' AND category NOT IN ('Cash Withdrawal','ATM Transfer','Internal Transfer') AND tx_date>=? AND tx_date<?"+(bank==null||bank.isEmpty()?"":" AND bank=?")+" GROUP BY 1";String[] args=(bank==null||bank.isEmpty())?new String[]{String.valueOf(from),String.valueOf(to)}:new String[]{String.valueOf(from),String.valueOf(to),bank};try(Cursor cur=getReadableDatabase().rawQuery(sql,args)){while(cur.moveToNext()){int month=cur.getInt(0);if(month>=1&&month<=12)out[month-1]=cur.getDouble(1);}}return out;}
    double[] monthlyIncome(int year,String bank){double[] out=new double[12];Calendar c=Calendar.getInstance();c.clear();c.set(year,Calendar.JANUARY,1);long from=c.getTimeInMillis();c.add(Calendar.YEAR,1);long to=c.getTimeInMillis();String sql="SELECT CAST(strftime('%m',tx_date/1000,'unixepoch','localtime') AS INTEGER),SUM(amount) FROM transactions WHERE type='Credit' AND category NOT IN ('Cash Withdrawal','ATM Transfer','Internal Transfer') AND tx_date>=? AND tx_date<?"+(bank==null||bank.isEmpty()?"":" AND bank=?")+" GROUP BY 1";String[] args=(bank==null||bank.isEmpty())?new String[]{String.valueOf(from),String.valueOf(to)}:new String[]{String.valueOf(from),String.valueOf(to),bank};try(Cursor cur=getReadableDatabase().rawQuery(sql,args)){while(cur.moveToNext()){int month=cur.getInt(0);if(month>=1&&month<=12)out[month-1]=cur.getDouble(1);}}return out;}
    private Filter filter(String month,String bank){List<String>w=new ArrayList<>(),a=new ArrayList<>();w.add("1=1");if(month!=null&&!month.isEmpty()){try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("yyyy-MM",java.util.Locale.US);Calendar c=Calendar.getInstance();c.setTime(f.parse(month));c.set(Calendar.DAY_OF_MONTH,1);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);long from=c.getTimeInMillis();c.add(Calendar.MONTH,1);w.add("tx_date>=? AND tx_date<?");a.add(String.valueOf(from));a.add(String.valueOf(c.getTimeInMillis()));}catch(Exception ignored){}}if(bank!=null&&!bank.isEmpty()){w.add("bank=?");a.add(bank);}return new Filter(android.text.TextUtils.join(" AND ",w),a.toArray(new String[0]));}
    private static final class Filter{final String where;final String[]args;Filter(String w,String[]a){where=w;args=a;}}
    int count(){try(Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM transactions",null)){return c.moveToFirst()?c.getInt(0):0;}}
}
