const categories=['Fuel','Food & Groceries','Phone & Internet','Health','Education & Online','Bank Charges','Transport','Shopping','Bills','Income / Deposit','Internal Transfer','Other'];
const colors={'Fuel':'#f59e0b','Food & Groceries':'#ef8354','Phone & Internet':'#4361ee','Health':'#e54c56','Education & Online':'#9b5de5','Bank Charges':'#64748b','Transport':'#00a8e8','Shopping':'#f15bb5','Bills':'#14b8a6','Other':'#94a3b8'};
const transactions=[
 {id:1,date:'Jul 18 · 2:21 PM',bank:'Commercial',account:'Commercial - Card',type:'Debit',amount:488,category:'Phone & Internet',description:'Mobile service payment',note:''},
 {id:2,date:'Jul 18 · 12:43 PM',bank:'Commercial',account:'Commercial - Card',type:'Debit',amount:5000,category:'Cash Withdrawal',description:'ATM cash withdrawal',note:'Cash for the weekend'},
 {id:3,date:'Jul 17 · 6:12 PM',bank:'Commercial',account:'Commercial - Card',type:'Debit',amount:4269,category:'Food & Groceries',description:'Greenway Supermarket',note:''},
 {id:4,date:'Jul 16 · 4:09 PM',bank:'Commercial',account:'Commercial - Card',type:'Debit',amount:4500,category:'Education & Online',description:'Online course subscription',note:'Design course'},
 {id:5,date:'Jul 15 · 8:30 AM',bank:'Sampath',account:'Sampath',type:'Credit',amount:85000,category:'Income / Deposit',description:'Monthly salary',note:''},
 {id:6,date:'Jul 14 · 6:27 PM',bank:'Commercial',account:'Commercial - Card',type:'Debit',amount:1250,category:'Health',description:'City Pharmacy',note:''},
 {id:7,date:'Jul 12 · 9:18 AM',bank:'Seylan',account:'Seylan',type:'Debit',amount:6200,category:'Fuel',description:'Metro Fuel Station',note:''},
 {id:8,date:'Jul 10 · 4:07 PM',bank:'Commercial',account:'Commercial - Saving',type:'Credit',amount:20000,category:'Internal Transfer',description:'Own account transfer',note:''}
];
const accounts=[['Commercial - Card','Commercial','LKR 18,652.24'],['Commercial - Saving','Commercial','LKR 42,500.00'],['Sampath','Sampath','LKR 91,840.50'],['Seylan','Seylan','LKR 33,280.00'],['Cash','Cash','LKR 5,020.00']];
let page='home',activeTx=null,toastTimer;
const viewport=document.querySelector('#viewport'),title=document.querySelector('#page-title'),subtitle=document.querySelector('#page-subtitle');
const money=n=>'LKR '+Number(n).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2});
const counted=t=>!['Cash Withdrawal','ATM Transfer','Internal Transfer'].includes(t.category);
const filtered=()=>{const bank=document.querySelector('#bank-filter')?.value||'Commercial';return bank==='All banks'?transactions:transactions.filter(t=>t.bank===bank)};
function filters(){return `<div class="filter-card"><label><span>Month</span><select id="month-filter"><option>July 2026</option><option>June 2026</option><option>May 2026</option></select></label><label><span>Bank</span><select id="bank-filter"><option>Commercial</option><option>Sampath</option><option>Seylan</option><option>Cash</option><option>All banks</option></select></label></div>`}
function section(name,meta=''){return `<div class="section-title"><h3>${name}</h3><span>${meta}</span></div>`}
function home(){const list=filtered(),income=list.filter(t=>t.type==='Credit'&&counted(t)).reduce((s,t)=>s+t.amount,0),expense=list.filter(t=>t.type==='Debit'&&counted(t)).reduce((s,t)=>s+t.amount,0),opening=31971.08,closing=opening+income-expense;const cats={};list.filter(t=>t.type==='Debit'&&counted(t)).forEach(t=>cats[t.category]=(cats[t.category]||0)+t.amount);const rows=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([name,value])=>`<div class="spend-row card"><span class="dot" style="background:${colors[name]||'#94a3b8'}"></span><div class="row-copy"><strong>${name}</strong><div class="progress"><i style="width:${Math.min(100,value/(expense||1)*100)}%;background:${colors[name]||'#94a3b8'}"></i></div></div><span class="amount">${money(value)}</span></div>`).join('');return `${filters()}<div class="hero"><span class="cap">Current / closing balance</span><h3>${money(closing)}</h3><div class="opening">Opening balance&nbsp; ${money(opening)}</div><div class="metrics"><div class="metric"><span>Income</span><strong>${money(income)}</strong></div><div class="metric"><span>Expenses</span><strong>${money(expense)}</strong></div></div></div>${section('Spending overview','July 2026')}${rows||`<div class="card empty-note">No spending data for this selection.</div>`}`}
function txCard(t){return `<article class="tx card" data-id="${t.id}" tabindex="0" role="button" aria-label="Edit ${t.description}"><span class="tx-icon ${t.type.toLowerCase()}">${t.type==='Debit'?'−':'+'}</span><div class="row-copy"><strong>${t.description}</strong><small>${t.bank} · ${t.account} · ${t.category}</small>${t.note?`<small class="note">Note: ${t.note}</small>`:''}</div><div><div class="amount ${t.type.toLowerCase()}">${t.type==='Debit'?'−':'+'} ${money(t.amount)}</div><small>${t.date}</small></div></article>`}
function transactionPage(){return `${filters()}${section('Transactions','Tap to edit')}<div id="tx-list">${filtered().map(txCard).join('')}</div>`}
function analytics(){const expense=transactions.filter(t=>t.type==='Debit'&&counted(t)),cats={};expense.forEach(t=>cats[t.category]=(cats[t.category]||0)+t.amount);const total=expense.reduce((s,t)=>s+t.amount,0);const entries=Object.entries(cats).sort((a,b)=>b[1]-a[1]);let start=0;const stops=entries.map(([n,v])=>{const a=start,b=start+v/total*360;start=b;return `${colors[n]||'#94a3b8'} ${a}deg ${b}deg`}).join(',');const legend=entries.slice(0,5).map(([n,v])=>`<div><i style="background:${colors[n]||'#94a3b8'}"></i><span>${n}</span><strong>${Math.round(v/total*100)}%</strong></div>`).join('');const monthly=[18,23,16,31,26,38,29,42,34,48,39,52].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><i class="expense" style="height:${Math.max(10,v-12)}%"></i><span>${'JFMAMJJASOND'[i]}</span></div>`).join('');return `${filters()}${section('Expense distribution','Sample year')}<div class="card donut-wrap"><div class="donut" style="background:conic-gradient(${stops})"></div><div class="legend">${legend}</div></div>${section('Income vs expenses','2026')}<div class="card bars">${monthly}</div>${section('Highest spending')}<div class="setting-row card"><span class="account-icon">★</span><div class="row-copy"><strong>${entries[0][0]}</strong><small>${Math.round(entries[0][1]/total*100)}% of tracked expenses</small></div><strong class="amount debit">${money(entries[0][1])}</strong></div>`}
function accountPage(){return `${section('Your accounts','Tap in the Android app to edit')}${accounts.map((a,i)=>`<div class="account-row card"><span class="account-icon ${a[0]==='Cash'?'cash':''}">${a[0]==='Cash'?'C':'B'}</span><div class="row-copy"><strong>${a[0]}</strong><small>${a[1]} · Available balance</small></div><strong class="amount">${a[2]}</strong></div>`).join('')}<button class="primary-btn" id="demo-action">＋ Add account</button><div class="card empty-note">The live Android app updates balances automatically from supported transaction alerts.</div>`}
function settings(){return `${section('Monthly balances')}<div class="setting-row card"><span class="account-icon">O</span><div class="row-copy"><strong>Opening balance</strong><small>Automatic calculation</small></div><strong class="amount">LKR 31,971.08</strong></div><div class="setting-row card"><span class="account-icon cash">C</span><div class="row-copy"><strong>Closing balance</strong><small>Automatic calculation</small></div><strong class="amount">LKR 18,652.24</strong></div>${section('Automation')}<button class="primary-btn" id="demo-action">Import / refresh bank SMS</button><div class="card empty-note">This browser demo never reads SMS. The Android app processes supported alerts locally on the device.</div>${section('Categories')}${categories.filter(c=>!c.includes('Transfer')&&!c.includes('Income')).map(c=>`<span class="category-pill"><i style="background:${colors[c]||'#94a3b8'}"></i>${c}</span>`).join('')}<button class="outline-btn" id="reset-demo">Reset demo data</button>`}
function render(){const names={home:['Money Monitor','Your finances, automatically organized'],transactions:['Transactions','Review and refine every movement'],analytics:['Analytics','Understand where your money goes'],accounts:['Accounts','Balances across every wallet'],settings:['Settings','Customize your money monitor']};title.textContent=names[page][0];subtitle.textContent=names[page][1];viewport.innerHTML=page==='home'?home():page==='transactions'?transactionPage():page==='analytics'?analytics():page==='accounts'?accountPage():settings();viewport.scrollTop=0;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('#bank-filter,#month-filter').forEach(s=>s.addEventListener('change',render));document.querySelectorAll('.tx').forEach(el=>{el.addEventListener('click',()=>openEdit(+el.dataset.id));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openEdit(+el.dataset.id)}})});document.querySelector('#demo-action')?.addEventListener('click',()=>showToast('Demo action completed'));document.querySelector('#reset-demo')?.addEventListener('click',()=>showToast('Demo data reset'))}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render()}));
document.querySelector('#refresh').addEventListener('click',e=>{e.currentTarget.classList.remove('spinning');void e.currentTarget.offsetWidth;e.currentTarget.classList.add('spinning');showToast('No new sample transactions')});
function openEdit(id){activeTx=transactions.find(t=>t.id===id);document.querySelector('#modal-title').textContent=activeTx.description;const select=document.querySelector('#edit-category');select.innerHTML=categories.map(c=>`<option ${c===activeTx.category?'selected':''}>${c}</option>`).join('');document.querySelector('#edit-note').value=activeTx.note;document.querySelector('#modal').hidden=false;select.focus()}
function closeEdit(){document.querySelector('#modal').hidden=true;activeTx=null}
document.querySelector('#cancel-edit').addEventListener('click',closeEdit);document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeEdit()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEdit()});
document.querySelector('#edit-form').addEventListener('submit',e=>{e.preventDefault();activeTx.category=document.querySelector('#edit-category').value;activeTx.note=document.querySelector('#edit-note').value.trim();closeEdit();render();showToast('Transaction updated')});
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
render();
